name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest   
          pip install pylint  
          pip install black

      - name: Run pytest
        run: |
          pytest

      - name: Lint with Pylint on utils.py
        run: |
          pylint ./utils.py

      - name: Check code formatting with Black
        run: |
          black --check .
